[tool.poetry]
name = "tap-jira"
version = "0.0.1"
description = "`tap-jira` is a Singer tap for tap-jira, built with the Meltano Singer SDK."
readme = "README.md"
authors = ["Ethan Stein"]
keywords = [
    "ELT",
    "tap-jira",
]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = ">=3.9"
s3fs = { version = "==2025.5.1", optional = true }
requests = "~=2.32.2"

[tool.poetry.dependencies.singer-sdk]
version = "~=0.47.0"

[tool.poetry.group.dev.dependencies]
pytest = ">=8"

[tool.poetry.group.dev.dependencies.singer-sdk]
version = "*"
extras = ["testing"]

[tool.poetry.extras]
s3 = ["s3fs"]

[tool.mypy]
python_version = "3.9"
warn_unused_configs = true

[tool.ruff]
target-version = "py39"

[tool.ruff.lint]
select = ["ALL"]

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.lint.isort]
known-first-party = ["tap_jira"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
tap-jira = 'tap_jira.tap:TapJira.cli'
